### ISSUE TITLE
Add support for sending images

### ISSUE THREAD

**Issue by hmps** [manimul/chat-test#2]
# Request

- As an author (a user sending a message) I want to be able to send images using the chat. I also want to be able to see the image in the chat, to verify that it worked.
- As a consumer (a user receiving a message) I want to be able to view an image sent to me in the chat.

# Constraints

For this first version the chat only has to work with small photos (<10kb).  See an example below.

# Example
![image](https://user-images.githubusercontent.com/1231909/96327805-4b75e880-103d-11eb-90d2-6a7d45f8d3ba.png)

**Comment by manimul** [comment]
Hi @hmps I have pushed a commit with my solution. You can find it in the linked pull request
